language: cpp

sudo: required

branches:
  only:
    - master
    - coverity_scan

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EqS/6H54HYLRObOlmLLN9omXJMZk5oKhNnhlpsVtQVv6oESEFrZy+BINVSEhWffP367Ohl1zOn10YnwV8GzAN8EIqR+Csvg1K2kgMNdZTUhqPS4KvU67NScvCbbQUCcX/UrVAsz+347LGRZL9vmLLeNLW3pn5jKCLK/iWTcaLr+wp4GY9YaSwEYlSz332VSPvseyc3xTojWz2cQLPm9JPP/7Uv6jv0Kbh+MVW/yfkg+PJj8h0Xcc/L2GYyAD4w89IB0mW69jtkHHDnmh23LoJCzF7Dcbfc3aWirCG5NoPGA7wdWkLF1SUwG/b/VJgbwPD1ZQeSz0pyfFbdmZJRY4GaG7I3x44gfHPnAknHvf+8eqr9uEcpVy4KnKkP1c9D2nf4FkwmKM94DIVAN2MmsiSrjFYnK/4UQ9ly+FaUHpn7f9Aydn97qR0PSR/w9kfQRsCsVuRtI0Kp1g1JNOmCajJyIXMP4iJZFYRgAPQUSfvROpZe0c102rFk86maLFDu2kJ7And8R7Br2JAUFHtsNEFnc4KHYn7bV2znTQ+HTIZbrxmw5+BjG7omf9YkCc5sDOwr9fy068JTdOzyxe8vovbgTG2L25jB282WGDkY7gDv/aXnMAC3oIoAAZjLraMgOE3YIQDyrlrlLboWUcx6IldaqjeueIe/U3qS5yNkO7mgg="

matrix:
  include:
    # Coverity Scan (Linux Debug)
    - os: linux
      compiler: gcc
      before_install:
        - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
        coverity_scan:
          project:
            name: "simonjung1603/ModernCMake"
            description: "A CMake example"
          notification_email: simonjung1603@gmail.com
          build_command_prepend: "cov-configure --comptype gcc --compiler g++-5 --template && cmake -DCMAKE_CXX_COMPILER=g++-5 -DGEN_DOCS=OFF ."
          build_command: "cmake --build ."
          branch_pattern: coverity_scan
      if: branch = coverity_scan
      before_script: echo "Coverity Scan"
      script: echo "Coverity Scan"
    # Code coverage (Linux Debug)
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - lcov
      before_script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON -DGEN_DOCS=OFF ..
      script:
        - cmake --build . -- -j2
        # fix coverage - cmake --build . --target coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
      if: branch != coverity_scan
    # Linux Release
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="COMPILER=g++-5 && BUILD_TYPE=Release"
      if: branch != coverity_scan
    # OSX Debug
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Debug"
      if: branch != coverity_scan
    # OSX Release
    - os: osx
      osx_image: xcode9.2 
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      if: branch != coverity_scan
    - os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="COMPILER=msvc && BUILD_TYPE=Release"
      if: branch != coverity_scan
    - os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="COMPILER=msvc && BUILD_TYPE=Debug"
      if: branch != coverity_scan

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTING=ON -DGEN_DOCS=OFF ..

script:
  - cmake --build . # Build the code
  - cd MidiBuddyBuild
  - ctest --output-on-failure
  - cmake --build . --target install # Install the necessary files
